- module: eye
  name: right_eye
  canvas:
    pos:
      x: -60
      y: -150
    size:
      w: 50
      h: 50
    rotation: 0
  dofs:
    - name: horizontal
      servo:
        pin: 3
        mid: 1700
        min: -350
        max: +350
    - name: vertical
      servo:
        pin: 2
        mid: 1525
        min: +350
        max: -350
    - name: lid
      servo:
        pin: 4
        mid: 1500
        min: +300
        max: -350
      mapping:
        neutral: 0.5
        poly:
          # Alpha:Pos
          0:      0.50
          18:     0.50
          36:     0.50
          54:     0.50
          72:     0.50
          90:     0.80
          108:    0.80
          126:    0.80
          144:    0.50
          162:    0.50
          180:    0.50
          198:    0.40
          216:    0.40
          234:    0.40
          252:    0.25
          270:    0.25
          288:    0.50
          306:    0.50
          324:    0.50
          342:    0.50

- module: eye
  name: left_eye
  canvas:
    pos:
      x: 60
      y: -150
    size:
      w: 50
      h: 50
    rotation: 0
  dofs:
    - name: horizontal
      servo:
        pin: 13
        mid: 1550
        min: -350
        max: +350
    - name: vertical
      servo:
        pin: 12
        mid: 1525
        min: -350
        max: +350
    - name: lid
      servo:
        pin: 11
        mid: 1525
        min: -300
        max: +350
      mapping:
        neutral: 0.5
        poly:
          # Alpha:Pos
          0:      0.50
          18:     0.50
          36:     0.50
          54:     0.50
          72:     0.50
          90:     0.80
          108:    0.80
          126:    0.80
          144:    0.50
          162:    0.50
          180:    0.50
          198:    0.40
          216:    0.40
          234:    0.40
          252:    0.25
          270:    0.25
          288:    0.50
          306:    0.50
          324:    0.50
          342:    0.50

- module: mouth
  name: mouth
  canvas:
    pos:
      x: 0
      y: -55
    size:
      w: 150
      h: 50
    rotation: 10
  dofs:
    - name: left
      servo:
        pin: 5
        mid: 1550
        min: +400
        max: -300
      mapping:
        neutral: 0.2
        poly:
          # Alpha:Pos
          0:      0.50
          18:     0.70
          36:     0.70
          54:     0.40
          72:     0.0
          90:     0.0
          108:   -0.50
          126:   -0.50
          144:   -0.50
          162:   -0.50
          180:   -0.50
          198:   -1.0
          216:   -1.0
          234:   -0.25
          252:   -0.25
          270:    0.25
          288:    0.25
          306:    0.50
          324:    0.50
          342:    0.50
    - name: mid
      servo:
        pin: 6
        mid: 1525
        min: +400
        max: -250
      mapping:
        neutral: 0.5
        poly:
          # Alpha:Pos
          0:      1.0
          18:     0.50
          36:    -1.0
          54:    -1.0
          72:    -0.50
          90:    -1.0
          108:   -0.80
          126:   -0.80
          144:   -0.80
          162:    0.50
          180:    1.0
          198:    1.0
          216:    1.0
          234:    1.0
          252:    1.0
          270:    1.0
          288:    1.0
          306:    1.0
          324:    1.0
          342:    1.0
    - name: right
      servo:
        pin: 7
        mid: 1600
        min: -400
        max: +300
      mapping:
        neutral: 0.2
        poly:
          # Alpha:Pos
          0:      0.50
          18:     0.70
          36:     0.70
          54:     0.40
          72:     0.0
          90:     0.0
          108:   -0.50
          126:   -0.50
          144:   -0.50
          162:   -0.50
          180:   -0.50
          198:   -1.0
          216:   -1.0
          234:   -0.25
          252:   -0.25
          270:    0.25
          288:    0.25
          306:    0.50
          324:    0.50
          342:    0.50

- module: eyebrow
  name: right_eyebrow
  canvas:
    pos:
      x: -60
      y: -200
    size:
      w: 80
      h: 50
    rotation: -20
  dofs:
    - name: inner
      servo:
        pin: 0
        mid: 1625
        min: +200
        max: -300
      mapping:
        neutral: 0.0
        poly:
          # Alpha:Pos
          0:      0.25
          18:     0.50
          36:     0.70
          #54:     0.70
          #72:     0.70
          90:     0.70
          108:    0.50
          126:    0.25
          144:   -0.50
          162:   -0.50
          180:   -0.25
          198:    0.25
          216:    0.25
          234:   -0.25
          252:    0.25
          #270:    0.25
          #288:    0.25
          #306:    0.25
          324:    0.25
          342:    0.50
    - name: outer
      servo:
        pin: 1
        mid: 1625
        min: -200
        max: +250
      mapping:
        neutral: 0.0
        poly:
          # Alpha:Pos
          0:      0.0
          18:     0.0
          36:     0.0
          54:     0.0
          72:     0.25
          90:     0.25
          108:    0.25
          126:    0.25
          144:    0.25
          162:    0.25
          180:    0.25
          198:   -0.25
          216:   -0.50
          234:   -0.25
          252:   -0.25
          270:   -0.25
          288:   -0.25
          306:    0.0
          324:    0.25
          342:    0.25

- module: eyebrow
  name: left_eyebrow
  canvas:
    pos:
      x: 60
      y: -200
    size:
      w: 80
      h: 50
    rotation: 30
  dofs:
    - name: inner
      servo:
        pin: 14
        mid: 1525
        min: -200
        max: +300
      mapping:
        neutral: 0.0
        poly:
          # Alpha:Pos
          0:      0.25
          18:     0.50
          36:     0.70
          54:     0.70
          72:     0.70
          90:     0.70
          108:    0.50
          126:    0.25
          144:   -0.50
          162:   -0.50
          180:   -0.25
          198:    0.25
          216:    0.25
          234:   -0.25
          252:    0.25
          270:    0.25
          288:    0.25
          306:    0.25
          324:    0.25
          342:    0.50
    - name: outer
      servo:
        pin: 15
        mid: 1550
        min: +200
        max: -250
      mapping:
        neutral: 0.0
        poly:
          # Alpha:Pos
          0:      0.0
          18:     0.0
          36:     0.0
          54:     0.0
          72:     0.25
          90:     0.25
          108:    0.25
          126:    0.25
          144:    0.25
          162:    0.25
          180:    0.25
          198:   -0.25
          216:   -0.50
          234:   -0.25
          252:   -0.25
          270:   -0.25
          288:   -0.25
          306:    0.0
          324:    0.25
          342:    0.25
