audio:
  master_volume: 67
  tts_engine: !!python/unicode picotts
general:
  password: RobotOno
  robot_name: !!python/unicode Ono
wireless:
  channel: 6
  password: RobotOno
  ssid: !!python/unicode Cesar's Ono
