audio:
  master_volume: 91
  tts_engine: !!python/unicode pico
  tts_gender: !!python/unicode m
  tts_language: !!python/unicode nl
general:
  password: opsoro
  robot_name: !!python/unicode Ono
wireless:
  channel: 6
  password: opsoro
  ssid: !!python/unicode OpSoRo_Robot
