general:
  robot_name: Ono
  password: opsoro123

alive:
  aliveness: 30
  blink: true
  gaze: true

audio:
  master_volume: 60
  tts_engine: espeak
  tts_language: nl
  tts_gender: m

wireless:
  ssid: OPSORO-bot
  password: opsoro123
  channel: 6
